### ISSUE TITLE
Mancato accesso al wallet

### ISSUE THREAD

**Issue by Salv72** [napoliblockchain/napay-docs#1]
Ciao Sergio
Ho provato ad accedere di nuovo, ma senza risultati positivi.
Forse perchè non sono un commerciante?

**Comment by jambtc** [comment]
Al momento il wallet può essere utilizzato esclusivamente dai commercianti. Magari prossimamente lo attiveremo anche ai soci standard.
Se vuoi fare un test di utilizzo puoi iscriverti alla piattaforma di test  napay.napoliblockchain.tk.
Non preoccuparti per il pagamento; trattandosi di test faremo una transazione fittizia

**Comment by jambtc** [comment]
ho fatto una verifica sul sito di test e puoi registrarti. Ricorda che devi selezionare persona giuridica per simulare un commerciante.

**Comment by Salv72** [comment]
Ok grazie, credo che attendo quando si creerà l'attivazione del Wallet anche per i soci standard!
