### ISSUE TITLE
[Bolt] Nuovo menu attività aderenti

### ISSUE THREAD

**Issue by jambtc** [napoliblockchain/napay-docs#26]
Nuovo Menù: ATTIVITA' ADERENTI
Nome attività, cliccando si inviano verso l'indirizzo dell'attivà commerciale.
Felice

**Comment by jambtc** [comment]
Conviene accorpare i due menù in uno solo.

Ad esempio se è possibile:

1) Dopo logo BOLT, un tasto "Attività aderenti". Cliccando sul tasto compare: CERCA : e sotto....

Nome attività commerciale (nome breve), ad esempio:

Pasticceria Carraturo (Piazza Leone, Napoli) >Mappa< Tel: 0000000 Token accettati: 1 TTS ogni 10 € (utilizza) 3 TTS ogni 15 € (utilizza)

Token in premio 0,1 Token per prodotto consumato (ricevi)

Cliccando su utilizza o su ricevi si compone automaticamente la schermata di invio o la macchina fotografica per la ricezione.

**Comment by chiacchio79** [comment]
Le "regole" di ricezione/uso dei TTS per ogni attività aderente, pensavo di pubblicizzarle anche sul sito e potresti semplicemente linkare la pagina dedicata, per non avere dati ridondanti su sito ed app

**Comment by jambtc** [comment]
Può accadere che un commerciante cambi in corso d'opera la modalità di erogazione  Token? Ad esempio passa dal 5% al 10%? 
In effetti cambiare solo la descrizione sul sito io la app non la modifico perché il link è sempre lo stesso.

**Comment by chiacchio79** [comment]
Secondo quanto ho previsto nel regolamento si, il commerciante può cambiare le proprie politiche nell'accettazione dei TTS, ma questo vale se il regolamento sarà preso così come l'ho scritto.

**Comment by jambtc** [comment]
@chiacchio79 ho implementato il menù nel wallet. Mi servono però i link alle pagine sul nostro sito con le informazioni da mostrare. 

Potremmo addirittura creare un widget per wordpress.
Potrebbe funzionare così:
IL commerciante dentro l'app inserisce i parametri del token (o glie li inseriamo noi) ma in un punto centralizzato vanno inseriti questi parametri.
Sul sito si crea la pagina del commerciante. Il widget tramite API, carica i parametri e li visualizza.
Bolt mostra il link a quella pagina.

**Comment by jambtc** [comment]
chiuso
