### ISSUE TITLE
Bolt: inserire recaptha2 in ripristino pwd, form, bugs e login

### ISSUE THREAD

**Issue by jambtc** [napoliblockchain/napay-docs#27]

**Comment by jambtc** [comment]
sono arrivate mail di spam. pertanto è necessario avere un sistema che possa bloccare i bot

**Comment by jambtc** [comment]
https://www.codexworld.com/google-invisible-recaptcha-with-php/

**Comment by opasch** [comment]
ma da dove sono arrivate queste mail di spam?

Il giorno sab 8 feb 2020 alle ore 13:16 jambtc <notifications@github.com>
ha scritto:

**Comment by Tommasone** [comment]
Non sono di spam, e' Sergio che ci assegna i casi su github :D

Ciao
T

Il giorno lun 10 feb 2020 alle ore 10:11 opasch <notifications@github.com>
ha scritto:

**Comment by opasch** [comment]
ho capito è che lui mi ha assegnato un task per gestire degli spam che
arrivano, quindi volevo sapere a quali spam si riferisse.

Il giorno lun 10 feb 2020 alle ore 10:25 Tommasone <notifications@github.com>
ha scritto:

**Comment by jambtc** [comment]
sono arrivate su info@napoliblockchain.it utilizzando il form per il bug di BOLT

**Comment by opasch** [comment]
Devi mettere un CAPTCHA

**Comment by jambtc** [comment]
Messo reCaptcha2 in tutte le form di tutte le 4 app
