### ISSUE TITLE
Napay: Consensi: il socio deve poter modificare quello sul marketing.

### ISSUE THREAD

**Issue by jambtc** [napoliblockchain/napay-docs#28]

**Comment by jambtc** [comment]
Non so se vedete che vi ho aggiunto. Mi serve per capire come implementare questa operazione.
Deve esserci uno storico dei movimenti o basta solo l'ultimo consenso (assegnato/tolto)?

Deve esserci un link che richiama la documentazione al consenso dato?

**Comment by Tommasone** [comment]
Se vogliamo essere pignoli, sarebbe necessario avere lo storico perché così
sappiamo in un determinato intervallo di tempo se l'utente poteva accettare
o meno comunicazioni promozionali. Ed in caso di controversie, glielo
mostriamo.

Saluti
T

Il ven 7 feb 2020, 09:52 jambtc <notifications@github.com> ha scritto:

**Comment by chiacchio79** [comment]
A prescindere dallo storico, che se fattibile è meglio averlo, per dare un minimo di validità legale al dato che eventualmente si porta in giudizio in caso di controversia, dovresti almeno far viaggiare la conferma di iscrizione/dis-iscrizione su mail, così da lasciare una minima traccia della volontà dell'utente... PEC sarebbe il top. Naturalmente ciò non è realisticamente attuabile e visto che nessuno ti fa causa per una mail pubblicitaria, teniamoci anche lo storico se non è un grosso impegno.

**Comment by jambtc** [comment]
habemus inscriptio et historicus
