### ISSUE TITLE
Napay: mailing list ai soci x comunicazioni generiche

### ISSUE THREAD

**Issue by jambtc** [napoliblockchain/napay-docs#32]

**Comment by jambtc** [comment]
quali possono essere Gli eventi oltre le transazioni? 
- sollecito pagamento  / promemoria scadenza 
.
.
.
secondo me è inutile visto che è già previsto l'invio di una mail.

**Comment by jambtc** [comment]
piuttosto si può pensare a fare una funzione che invii mail ai soci x comunicare la prossima riunione

**Comment by jambtc** [comment]
creare dei templates x 
- nuova riunione 
- avviso generico

**Comment by chiacchio79** [comment]
Ci lavoro io lunedì/martedì

**Comment by jambtc** [comment]
@chiacchio79 sei riuscito a scrivere qualcosa? Bastano poche righe che per il format utilizzo quello già in uso.
Oppure stavo pensando di creare un format x le nuove riunioni con questa form:
Data riunione
Luogo riunione
Ordini del giorno
Senza necessità di salvare nulla. 
Sulla conferma partono le mail a tutti gli iscritti.

**Comment by chiacchio79** [comment]
Eccomi, si il template usa lo stesso e direi in questo modo:

Per gli eventi
Oggetto/Titolo (quello azzurro): **Assemblea straordinaria** / **Primo Pizzachain!** / ecc....
Testo: Ciao **Tizio**,
l'associazione Napoli Blockchain ETS è felice di invitarti all'evento **"[oggetto]"** che si terrà il giorno xx/xx/xxxx alle ore xx:xx presso xxxxxxxxxxxxxxxxxxxx.

Il programma dell'evento prevede:
- Discordo del presidente
- Buffet
- Balli di gruppo
- Pizza finale

La tua partecipazione è importante ... bla bla bla...... questo va comunque scritto ogni volta in funzione dell'evento.

Per le comunicazioni generiche, basta il titolo azzurro ed il testo va scritto di volta in volta.

Non so se conviene creare un form mail, finisce che poi col tempo ci servirà qualcosa di più performante quindi direi di usare qualche strumento esistente (mailup, mailchimp, sendinblue, ecc...) che per bassi volumi sono free.

**Comment by chiacchio79** [comment]
Attento all'html del template, dalla mail che hai inviato per il rinnovo iscrizione noto che c'è un margin-top di 28px per i <p>, che allarga inutilmente la spaziatura verticale del testo.

**Comment by jambtc** [comment]
allora, ho sostituito tutti i 28px con 10px, inoltre ho tagliato i margini superiore e inferiore dell'immagine.

Il menu lo chiamo mail list, anche in italiano (la traduzione letterale è pessima)

**Comment by jambtc** [comment]
Ho concluso il form. Mi potete dire cosa mettere in bla bla bla? Così chiudo la issue e la carico nella nuova versione
