### ISSUE TITLE
[Bolt] Accorpamento menù

### ISSUE THREAD

**Issue by jambtc** [napoliblockchain/napay-docs#66]
Per eliminare un menù consiglio di lasciare solo quello in alto con:
Wallet, Transazioni, Contatti, Profilo, Impostazioni, Segnala errori (non bug)
Mentre nel menù a tendina sotto al nome utente solo ESCI.
Perchè altrimenti ti devi ricordare dove sta impostazioni.
Felice

**Comment by chiacchio79** [comment]
Sono d'accordo con Felice, unico menù è più semplice, metterei pure ESCI sotto lo stesso menù

**Comment by jambtc** [comment]
Aperto new branch menu-merging

**Comment by jambtc** [comment]
Chiuso
