### ISSUE TITLE
[Bolt] Due nuovi voci: Chi accetta i buoni, dove posso guadagnare i buoni

### ISSUE THREAD

**Issue by FeliceBalsamo** [napoliblockchain/napay-docs#78]
In alto in bolt c'e' molto spazio.
Nello spazio bianco in alto, si dovrebbe mettere un tasto:
DOVE SPENDERE I BUONI SCONTI (nome da accorciare)

e un altro

DOVE OTTENRE BUONI SCONTI (nome da accorciare)

Cliccando: Dove spendere si va su un sito con l'elenco delle attività commerciali ecc...
Cliccando su DOVE OTTENERE ... idem 

I nomi dei due tasti deve essere breve, del tipo:
     BUONI SCONTO
[SPENDI]  [GUADAGNA]

**Comment by jambtc** [comment]
Intendi magari 2 pulsanti? Oppure integrare nel menu?

**Comment by jambtc** [comment]
![Polish_20200220_214013497](https://user-images.githubusercontent.com/30697838/74976790-b842cf80-5429-11ea-9436-812a72c430b7.jpg)

**Comment by jambtc** [comment]
duplicato #26, #77, #78

**Comment by jambtc** [comment]
closing with #26
