### ISSUE TITLE
Coronavirus: notifica assembramento 

### ISSUE THREAD

**Issue by FeliceBalsamo** [napoliblockchain/napay-docs#90]
Considerando il particolare momento dovuto al coronavirus, per diffondere sia il token che le buone azioni per ridurre il rischio contagio, si potrebbe aggiungere a BOLT la funzione di avviso assembramento. 

BOLT verifica la presenza di un certo numero di cellulari e avvisa l'utente di allontanarsi da quella zona. 
Quando si allontana potrebbe ricevere in premio un token. Ma diciamo che il premio è opzionale. 
Sarebbe utile invece che bolt rilevi troppe persone vicine. 
Potrebbe rilevarlo dal numero di dispositivi BT attivi o magari se c'è possibilità in altro modo, accedendo alla posizione delle celle e da qualche altra informazione.

Ho trovato questa app (ma ne esistono tante) che rilevano oggetti vicino che rilascino onde elettromagnetiche. Come spunto: https://play.google.com/store/apps/details?id=fr.inria.es.electrosmart

**Comment by opasch** [comment]
mavafancul 😀😀😀😀

Il giorno mar 10 mar 2020 alle ore 18:05 jambtc <notifications@github.com>
ha scritto:

**Comment by jambtc** [comment]
In realtà implementando questa funzione, si potrebbe ricevere un messaggio quando si è vicini ad un commerciante che riceve token. 
Il link di Felice controlla le onde elettromagnetiche che via web credo sia impossibile da verificare, a meno di ulteriori avanzamenti delle pwa. Mentre è già possibile adesso tracciare la geolocalizzazione tramite GPS. Richiedendo l'attivazione all'utente è possibile tracciare la posizione degli smartphone.
Una funzione potrebbe tracciarne e salvare la posizione dell'utente.
Una funzione centrale, invece, (tipo watch tower)  verifica che queste posizioni siano nei paraggi di qualche commerciante, oppure, come dice Felice, non ci sia un assembramento. 
In realtà a parole è facile, ma abbiamo la necessita di farlo in breve tempo, che adesso non c'è.

Intanto, metto qui 2 link che potrebbero essere utili allo scopo, soprattutto per il salvataggio dei dati. Poi per la gestione dei dati e l'invio dei messaggi si può agire anche successivamente.

https://medium.com/@onejohi/introducing-geolocation-in-your-pwas-65713faba51a

https://love2dev.com/blog/html-geolocation/

**Comment by opasch** [comment]
io non perderei tempo con queste cose. Pensavo fosse uno scherzo.

Il giorno mar 10 mar 2020 alle ore 18:26 jambtc <notifications@github.com>
ha scritto:
